name: hee8_lb
description: HEE8 Leaderboard.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: HindSiliguri
      fonts:
        - asset: assets/fonts/HindSiliguri/HindSiliguri-Regular.ttf
        - asset: assets/fonts/HindSiliguri/HindSiliguri-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter.ttf
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans/IBMPlexSans-Bold.ttf
